 pipeline {
  agent any
  environment {
      SERVICE_NAME = "eureka-service"
      GIT_URL = "https://github.com/MarianoLopez/SpringCloud"
      M2_HOME = '/home/jenkins/.m2'
      //used by dockerBuildAndPublish
      NEXUS_URL = 'localhost'
      NEXUS_DOCKER_PORT = 8082
   }
  stages {
    stage('Build') {
      agent {
        docker {
          image 'maven:3.6.3-jdk-14'
          args '-v ${M2_HOME}:/root/.m2 -e BRANCH_NAME=${env.BRANCH_NAME}'
        }
      }
      steps {
        git url: "${GIT_URL}", branch: "${BRANCH_NAME}"
        dir(path: "${SERVICE_NAME}") {
          sh '/jenkins_scripts/mavenBuild.sh ./pom.xml'
          stash(name: "build-${SERVICE_NAME}", includes: 'target/**')
        }

      }
    }

    stage('Deploy docker image') {
      steps {
        git url: "${GIT_URL}", branch: "${env.BRANCH_NAME}"
        dir(path: "${SERVICE_NAME}") {
          unstash "build-${SERVICE_NAME}"
          sh "/jenkins_scripts/dockerBuildAndPublish.sh $SERVICE_NAME"
        }
      }
    }

    stage('Clean workspace') {
      steps {
        sh "/jenkins_scripts/dockerPrune.sh"
        cleanWs()
      }
    }

  }
}