version: '3'
services:
  eureka-service:
    image: eureka-service:snapshot
    container_name: eureka-service-snapshot
    ports:
     - 8761:8761
  gateway-service:
    image: gateway-service:snapshot
    container_name: gateway-service-snapshot
    ports:
     - 9000:9000
    environment:
      EUREKA_HOST: eureka-service
    depends_on:
      - eureka-service
  user-service:
    image: user-service:snapshot
    container_name: user-service-snapshot
    depends_on:
     - mariadb
     - eureka-service
    environment:
      EUREKA_HOST: eureka-service
      DB_HOST: mariadb
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./maria_config/my.cnf:/etc/mysql/my.cnf
      - ./maria_scripts:/docker-entrypoint-initdb.d