version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
      - /home/jenkins:/home
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - ./nexus-data:/nexus-data
    ports:
      - 8081:8081