 pipeline {
  agent any
  environment {
      SERVICE_NAME = "gateway-service"
      M2_HOME = '/home/jenkins/.m2'
      NEXUS_URL = 'localhost'
      NEXUS_DOCKER_PORT = 8082
   }
  stages {
    stage('Build') {
      agent {
        docker {
          image 'maven:3.6.3-jdk-14'
          args '-v ${M2_HOME}:/root/.m2'
        }
      }
      steps {
        checkout scm
        dir(path: "${SERVICE_NAME}") {
          sh '/jenkins_scripts/mavenBuild.sh ./pom.xml'
          stash(name: "build-${SERVICE_NAME}", includes: 'target/**')
        }

      }
    }

    stage('Tests') {
      agent {
        docker {
          image 'maven:3.6.3-jdk-14'
          args '-v ${M2_HOME}:/root/.m2'
        }
      }
      options {
        skipDefaultCheckout()
      }
      steps {
        dir(path: "${SERVICE_NAME}") {
          unstash "build-${SERVICE_NAME}"
          sh '/jenkins_scripts/mavenTest.sh ./pom.xml'
        }
      }
       post {
          always {
              junit '**/target/surefire-reports/*.xml'
          }
      }
    }

    stage('Deploy docker image') {
      options {
        skipDefaultCheckout()
      }
      steps {
        dir(path: "${SERVICE_NAME}") {
          unstash "build-${SERVICE_NAME}"
          sh "/jenkins_scripts/dockerBuildAndPublish.sh $SERVICE_NAME"
        }
      }
    }

    stage('Clean workspace') {
      steps {
        sh "/jenkins_scripts/dockerPrune.sh"
        cleanWs()
      }
    }

  }
}